[info]
name = "scrub"
version = "0.1.0"
authors = ["Tim Steenvoorden <tim.steenvoorden@gmail.com>"]

[[dependencies]]
name = "clean-platform"
version = "0.100.0"
path = "../clean-platform"

[[dependencies]]
name = "clean-generics"
version = "2.4.0"
path = "../clean-generics"

[[dependencies]]
name = "clean-stdenv"
version = "2.4.0"
path = "../clean-stdenv"

#[executables.scrub]
#name = default: package.name
#path = default: "src/Main.cl"

